/* nis2 tg-cta widget — generated by tools/telegram_bot/build_bot.py */
(function () {
  function add() {
    if (document.getElementById("nis2-tg-cta")) return;
    var box = document.createElement("div");
    box.id = "nis2-tg-cta";
    box.style.cssText = "text-align:center;margin:1.5rem auto;padding:1rem;display:flex;gap:.6rem;flex-wrap:wrap;justify-content:center;";
    var b = document.createElement("a");
    b.href = "https://t.me/nis2network_bot?start=pl"; b.target = "_blank"; b.rel = "noopener";
    b.textContent = "🛡️ Sprawdź, czy podlegasz NIS2 (2 min)";
    b.style.cssText = "display:inline-flex;align-items:center;gap:.4rem;padding:.6rem 1.2rem;border-radius:999px;background:#1e3a5f;color:#fff;font-size:.85rem;font-weight:700;text-decoration:none;";
    box.appendChild(b);
    (document.querySelector("footer") || document.body).appendChild(box);
  }
  if (document.readyState !== "loading") add();
  else document.addEventListener("DOMContentLoaded", add);
})();
